# Generated by Django 6.0.3 on 2026-04-10 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', 'Work'), ('break', 'Break')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.day')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('day', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.step')),
            ],
        ),
    ]
